### ISSUE TITLE
Problems building iOS version of app with the plugin

### ISSUE THREAD

**Issue by thunexy** [DFTinc/cordova-plugin-onyx#1]
Hello! I have been encountering errors when trying to build an iOS version using this plugin. Android works very fine but the iOS doesn't. Tried different solutions, all to no avail. Have attached the screenshot of the errors.

![screen shot 2017-07-28 at 2 32 08 pm](https://user-images.githubusercontent.com/30528516/28719373-a47940ee-73a1-11e7-94db-a1ea74364591.png)

**Comment by mjwheatley** [comment]
This plugin is not compatible with iOS simulator (architecture x86_64).  You must run your app on a hardware device.

**Comment by thunexy** [comment]
The problem is that the plugin is not making the app compile.

**Comment by mjwheatley** [comment]
What device do you have selected when compiling?

**Comment by thunexy** [comment]
I tried iPhone 5s, 6 and 7

**Comment by mjwheatley** [comment]
Your screenshot shows iPhone 5s (simulator).  Please connect a hardware device to your Mac or try generic hardware device and recompile.

**Comment by thunexy** [comment]
Okay, thank you

On Jul 28, 2017 6:58 PM, "Matthew Wheatley" <notifications@github.com>
wrote:

Your screenshot shows iPhone 5s (simulator). Please connect a hardware
device to your Mac or try generic hardware device and recompile.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DFTinc/cordova-plugin-onyx/issues/1#issuecomment-318721984>,
or mute the thread
